In [1]:
import numpy as np

In [39]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [3]:
arr1 = np.array([5,4,8,9])

In [4]:
arr1

array([5, 4, 8, 9])

In [7]:
arr1.ndim

1

In [8]:
arr2 = np.array([[58,98,65,25],[89,45,78,96]])

In [9]:
arr2

array([[58, 98, 65, 25],
       [89, 45, 78, 96]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [13]:
arr2.dtype

dtype('int32')

In [16]:
np.linspace(10,50)

array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

In [17]:
np.linspace(10,50,20)

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])

In [18]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
np.ones(10,dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [23]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [25]:
num = np.random.randint(45,65)

In [26]:
num

52

In [29]:
np.random.seed(1)
num2 = np.random.randint(45,65,100)

In [30]:
num2

array([50, 56, 57, 53, 54, 56, 50, 60, 45, 61, 46, 57, 52, 58, 51, 63, 50,
       63, 56, 55, 59, 63, 49, 54, 62, 45, 58, 54, 54, 52, 46, 45, 62, 53,
       58, 64, 60, 55, 53, 52, 48, 51, 62, 48, 49, 62, 56, 57, 61, 58, 64,
       54, 63, 60, 45, 49, 60, 47, 52, 53, 54, 48, 52, 49, 50, 64, 51, 53,
       45, 47, 55, 60, 60, 52, 64, 55, 59, 45, 46, 62, 58, 48, 45, 58, 51,
       51, 47, 57, 56, 52, 58, 53, 56, 57, 56, 49, 52, 52, 58, 49])

In [31]:
num2 = num2.reshape(10,10)

In [32]:
num2

array([[50, 56, 57, 53, 54, 56, 50, 60, 45, 61],
       [46, 57, 52, 58, 51, 63, 50, 63, 56, 55],
       [59, 63, 49, 54, 62, 45, 58, 54, 54, 52],
       [46, 45, 62, 53, 58, 64, 60, 55, 53, 52],
       [48, 51, 62, 48, 49, 62, 56, 57, 61, 58],
       [64, 54, 63, 60, 45, 49, 60, 47, 52, 53],
       [54, 48, 52, 49, 50, 64, 51, 53, 45, 47],
       [55, 60, 60, 52, 64, 55, 59, 45, 46, 62],
       [58, 48, 45, 58, 51, 51, 47, 57, 56, 52],
       [58, 53, 56, 57, 56, 49, 52, 52, 58, 49]])

In [34]:
num2[0,5]

56

In [38]:
num2[3:8,3:6]

array([[53, 58, 64],
       [48, 49, 62],
       [60, 45, 49],
       [49, 50, 64],
       [52, 64, 55]])

In [47]:
num3 = np.arange(1,101)

In [48]:
num3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# Exercise
# generate a random number between 35 and 75 with total of 150
# using the seed number of 5
# reshape it to 15 rows and 10 columns
# select out all the values from 5 to 10 on the row and 4 to 8 on the column

In [49]:
np.random.seed(5)
num4 = np.random.randint(35,75,150)

In [50]:
num4 = num4.reshape(15,10)

In [51]:
num4

array([[70, 49, 73, 51, 44, 43, 71, 74, 62, 65],
       [51, 42, 47, 50, 74, 51, 62, 48, 46, 36],
       [65, 55, 57, 53, 44, 36, 53, 74, 51, 49],
       [40, 35, 51, 39, 71, 62, 66, 37, 39, 73],
       [54, 54, 53, 42, 71, 65, 46, 38, 36, 38],
       [62, 49, 62, 64, 68, 60, 56, 42, 51, 65],
       [49, 61, 66, 44, 73, 51, 40, 69, 59, 48],
       [66, 67, 47, 40, 49, 65, 53, 35, 74, 42],
       [57, 51, 35, 43, 61, 72, 65, 46, 40, 57],
       [40, 53, 62, 64, 59, 68, 63, 50, 41, 70],
       [55, 43, 67, 53, 48, 63, 53, 52, 57, 54],
       [63, 54, 39, 53, 71, 55, 67, 45, 66, 50],
       [57, 41, 44, 65, 49, 37, 54, 35, 43, 43],
       [42, 47, 55, 43, 45, 57, 43, 67, 50, 40],
       [70, 71, 35, 37, 37, 62, 36, 58, 36, 58]])

In [52]:
num4[5:11,4:9]

array([[68, 60, 56, 42, 51],
       [73, 51, 40, 69, 59],
       [49, 65, 53, 35, 74],
       [61, 72, 65, 46, 40],
       [59, 68, 63, 50, 41],
       [48, 63, 53, 52, 57]])

In [53]:
num4[5:11,4:9] = 40

In [54]:
num4

array([[70, 49, 73, 51, 44, 43, 71, 74, 62, 65],
       [51, 42, 47, 50, 74, 51, 62, 48, 46, 36],
       [65, 55, 57, 53, 44, 36, 53, 74, 51, 49],
       [40, 35, 51, 39, 71, 62, 66, 37, 39, 73],
       [54, 54, 53, 42, 71, 65, 46, 38, 36, 38],
       [62, 49, 62, 64, 40, 40, 40, 40, 40, 65],
       [49, 61, 66, 44, 40, 40, 40, 40, 40, 48],
       [66, 67, 47, 40, 40, 40, 40, 40, 40, 42],
       [57, 51, 35, 43, 40, 40, 40, 40, 40, 57],
       [40, 53, 62, 64, 40, 40, 40, 40, 40, 70],
       [55, 43, 67, 53, 40, 40, 40, 40, 40, 54],
       [63, 54, 39, 53, 71, 55, 67, 45, 66, 50],
       [57, 41, 44, 65, 49, 37, 54, 35, 43, 43],
       [42, 47, 55, 43, 45, 57, 43, 67, 50, 40],
       [70, 71, 35, 37, 37, 62, 36, 58, 36, 58]])

In [56]:
num4[num4 > 40] 

array([70, 49, 73, 51, 44, 43, 71, 74, 62, 65, 51, 42, 47, 50, 74, 51, 62,
       48, 46, 65, 55, 57, 53, 44, 53, 74, 51, 49, 51, 71, 62, 66, 73, 54,
       54, 53, 42, 71, 65, 46, 62, 49, 62, 64, 65, 49, 61, 66, 44, 48, 66,
       67, 47, 42, 57, 51, 43, 57, 53, 62, 64, 70, 55, 43, 67, 53, 54, 63,
       54, 53, 71, 55, 67, 45, 66, 50, 57, 41, 44, 65, 49, 54, 43, 43, 42,
       47, 55, 43, 45, 57, 43, 67, 50, 70, 71, 62, 58, 58])

In [70]:
num4[num4 ==40]

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

In [71]:
np.sum(num4)

7512

In [73]:
np.max(num4)

74

In [74]:
np.min(num4)

35

In [75]:
np.mean(num4)

50.08

In [76]:
np.log10(num4)

array([[1.84509804, 1.69019608, 1.86332286, 1.70757018, 1.64345268,
        1.63346846, 1.85125835, 1.86923172, 1.79239169, 1.81291336],
       [1.70757018, 1.62324929, 1.67209786, 1.69897   , 1.86923172,
        1.70757018, 1.79239169, 1.68124124, 1.66275783, 1.5563025 ],
       [1.81291336, 1.74036269, 1.75587486, 1.72427587, 1.64345268,
        1.5563025 , 1.72427587, 1.86923172, 1.70757018, 1.69019608],
       [1.60205999, 1.54406804, 1.70757018, 1.59106461, 1.85125835,
        1.79239169, 1.81954394, 1.56820172, 1.59106461, 1.86332286],
       [1.73239376, 1.73239376, 1.72427587, 1.62324929, 1.85125835,
        1.81291336, 1.66275783, 1.5797836 , 1.5563025 , 1.5797836 ],
       [1.79239169, 1.69019608, 1.79239169, 1.80617997, 1.60205999,
        1.60205999, 1.60205999, 1.60205999, 1.60205999, 1.81291336],
       [1.69019608, 1.78532984, 1.81954394, 1.64345268, 1.60205999,
        1.60205999, 1.60205999, 1.60205999, 1.60205999, 1.68124124],
       [1.81954394, 1.8260748 , 1.6720978

In [77]:
np.argmin(num4)

31

In [78]:
np.argmax(num4)

7

In [84]:
np.percentile(num4,100)

74.0